# coding: utf-8
from __future__ import unicode_literals

DEFAULT_ALLOW_CASH_COUNT = 30000
DEFAULT_COIN_CASH_PROPORTION = 1000
DEFAULT_NEW_PACKET = 6660
TOTAL_LEVEL = 800
ROUND_CASH = 300
ROUND_COUNT = 50
NEW_EXTEND_TIMES = 3


# 红包相关
PACKET_TYPE_NEW_CASH = 0
PACKET_TYPE_CASH = 1
PACKET_TYPE_EXTEND = 2
PACKET_TYPE_PHONE = 3
PACKET_TYPE_WITHDRAW = 4

STATUS_USED = 0
STATUS_UNUSE = 1
STATUS_EXPIRE = 2
