# coding: utf-8
from __future__ import unicode_literals

DEFAULT_ALLOW_CASH_COUNT = 30000
DEFAULT_ALLOW_CASH_RIGHT_COUNT = 5000
DEFAULT_COIN_CASH_PROPORTION = 1000
DEFAULT_NEW_PACKET = 6660
TOTAL_LEVEL = 800
ROUND_CASH = 30000
ROUND_COUNT = 700
NEW_EXTEND_TIMES = 3
DEFAULT_REWARD_COUNT = 10
DEFAULT_SONGS_COUNT = 5
DEFAULT_SONGS_THRESHOLD = 50


# 红包相关
PACKET_TYPE_NEW_CASH = 0
PACKET_TYPE_CASH = 1
PACKET_TYPE_EXTEND = 2
PACKET_TYPE_PHONE = 3
PACKET_TYPE_WITHDRAW = 4

STATUS_USED = 0
STATUS_UNUSE = 1
STATUS_EXPIRE = 2


DEFAULT_NEW_WITHDRAW_THRESHOLD = 30
DEFAULT_FIRST_WITHDRAW_THRESHOLD = 30000
DEFAULT_SECOND_WITHDRAW_THRESHOLD = 50000
DEFAULT_THIRD_WITHDRAW_THRESHOLD = 100000


NEW_WITHDRAW = 0
NORMAL_WITHDRAW = 1
