# coding: utf-8
from __future__ import unicode_literals

DEFAULT_ALLOW_CASH_COUNT = 30000
DEFAULT_ALLOW_CASH_RIGHT_COUNT = 1000
DEFAULT_COIN_CASH_PROPORTION = 1000
DEFAULT_NEW_PACKET = 6660
TOTAL_LEVEL = 800
ROUND_CASH = 30000
ROUND_COUNT = 1000
NEW_EXTEND_TIMES = 3
DEFAULT_REWARD_COUNT = 10
NEW_VERSION_REWARD_COUNT = 20
DEFAULT_SONGS_COUNT = 5
DEFAULT_SONGS_THRESHOLD = 0
DEFAULT_SONGS_TWO_COUNT = 3
DEFAULT_SONGS_TWO_THRESHOLD = 4000
DEFAULT_SONGS_THREE_COUNT = 1
DEFAULT_SONGS_THREE_THRESHOLD = 5000
DEFAULT_MAX_CASH_LIMIT = 25000
DEFAULT_SONGS_BONUS_THRESHOLD = 20

# 红包相关
PACKET_TYPE_NEW_CASH = 0
PACKET_TYPE_CASH = 1
PACKET_TYPE_EXTEND = 2
PACKET_TYPE_PHONE = 3
PACKET_TYPE_WITHDRAW = 4

STATUS_USED = 0
STATUS_UNUSE = 1
STATUS_EXPIRE = 2

STATUS_FAIL = 0
STATUS_REVIEW = 1
STATUS_FINISH = 2

STATUS_DESTROY = 0
STATUS_ENABLE = 1
STATUS_PAUSE = 2

DEFAULT_NEW_WITHDRAW_THRESHOLD = 30
DEFAULT_FIRST_WITHDRAW_THRESHOLD = 30000
DEFAULT_SECOND_WITHDRAW_THRESHOLD = 50000
DEFAULT_THIRD_WITHDRAW_THRESHOLD = 100000

NEW_WITHDRAW = 0
NORMAL_WITHDRAW = 1

EVENT_AD_STIMULATE_RIGHT = 1
EVENT_AD_STIMULATE_WRONG = 2
EVENT_AD_STIMULATE_FORCE_WRONG = 3
EVENT_AD_STIMULATE_FORCE_RIGHT = 4
EVENT_AD_CARD_RESDIA = 5
EVENT_AD_CARD_USERCENTER = 6
EVENT_AD_SPLASH = 7
